# Generated by Django 2.2.5 on 2019-09-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20190919_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
