# Generated by Django 2.2.5 on 2019-09-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banks', '0002_auto_20190917_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
