# Generated by Django 2.2.5 on 2019-09-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banks', '0003_auto_20190919_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='consultancy_type',
            field=models.CharField(choices=[('Retainer', 'Retainer'), ('Project', 'Project')], default='Retainer', max_length=50),
            preserve_default=False,
        ),
    ]
