# Generated by Django 2.2.5 on 2019-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banks', '0004_bank_consultancy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='consultancy_type',
            field=models.CharField(choices=[('', '--- Please Select Consultancy Type ---'), ('Retainer', 'Retainer'), ('Project', 'Project')], max_length=50),
        ),
    ]
