# Generated by Django 2.2.5 on 2019-09-18 09:26

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('technology_domain', models.CharField(max_length=130)),
                ('document_type', models.CharField(max_length=130)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('Qattachements', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='uploads/'), size=None)),
                ('Rattachements', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='uploads/'), size=None)),
                ('consultants', models.ManyToManyField(related_name='consultants', to=settings.AUTH_USER_MODEL)),
                ('spoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Q_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=30)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('requests_recieved', models.CharField(max_length=1200)),
                ('summary_of_response', models.TextField()),
                ('summary_of_workdone', models.TextField()),
                ('learnings', models.TextField()),
                ('consultants', models.ManyToManyField(related_name='consultants_invovled1', to=settings.AUTH_USER_MODEL)),
                ('spoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
