# Generated by Django 2.2.5 on 2019-09-18 11:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_auto_20190918_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Qattachements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='uploads/'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='Rattachements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='uploads/'), blank=True, null=True, size=None),
        ),
    ]
