# Generated by Django 2.2.5 on 2019-09-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0004_auto_20190919_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
