# Generated by Django 2.2.5 on 2019-09-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0005_queryfiles_responsefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='queryfiles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='queryfiles', to='Reports.QueryFiles'),
        ),
        migrations.AddField(
            model_name='report',
            name='responsefiles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responsefiles', to='Reports.ResponseFiles'),
        ),
    ]
