# Generated by Django 2.2.5 on 2019-09-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0007_auto_20190919_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryfiles',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='queryfiles', to='Reports.Report'),
        ),
        migrations.AddField(
            model_name='responsefiles',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responsefiles', to='Reports.Report'),
        ),
    ]
