# Generated by Django 2.2.5 on 2019-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
